suggestion=[
  "American Restaurant",
  "Cricket Ground",
  "Park",
  "Ice Cream Shop",
  "Pub",
  "Chinese Restaurant",
  "Toy / Game Store",
  "Burger Joint",
  "Plaza",
  "Hotel",
  "Deli / Bodega",
  "Lounge",
  "Breakfast Spot",
  "Shopping Mall",
  "Italian Restaurant",
  "Furniture / Home Store",
  "Asian Restaurant",
  "Japanese Restaurant",
  "Bookstore",
  "French Restaurant",
  "Bubble Tea Shop",
  "Brewery",
  "Steakhouse",
  "Cupcake Shop",
  "Afghan Restaurant",
  "Indian Restaurant",
  "Sushi Restaurant",
  "Clothing Store",
  "Café",
  "Bakery",
  "Cocktail Bar",
  "Pizza Place",
  "Coffee Shop",
  "Tea Room",
  "Andhra Restaurant",
  "Athletics & Sports",
  "Gym / Fitness Center",
  "Arcade",
  "Electronics Store",
  "Fried Chicken Joint",
  "Vegetarian / Vegan Restaurant",
  "Bed & Breakfast",
  "Soccer Stadium",
  "Women's Store",
  "Gym",
  "Korean Restaurant",
  "Dessert Shop",
  "Wine Bar",
  "Mediterranean Restaurant",
  "Arts & Crafts Store",
  "Seafood Restaurant",
  "Racetrack",
  "Concert Hall",
  "Eastern European Restaurant",
  "Theater",
  "South Indian Restaurant",
  "Karnataka Restaurant",
  "Movie Theater",
  "Motorcycle Shop",
  "Art Gallery",
  "Boutique",
  "Bagel Shop",
  "Snack Place",
  "Botanical Garden",
  "Mexican Restaurant",
  "Spa",
  "Track Stadium",
  "Bar",
  "Hockey Arena",
  "Stadium",
  "Capitol Building",
  "Miscellaneous Shop",
  "Fast Food Restaurant",
  "Music Store",
  "BBQ Joint",
  "Middle Eastern Restaurant",
  "Department Store",
  "Hotel Bar",
  "Donut Shop",
  "Thai Restaurant",
  "Modern European Restaurant",
  "Candy Store",
  "Gaming Cafe",
  "Chocolate Shop",
  "German Restaurant",
  "Diner",
  "Nightclub",
  "Restaurant",
  "Music Venue",
  "Burrito Place",
  "Outlet Store",
  "Vietnamese Restaurant",
  "Butcher",
  "Tex-Mex Restaurant",
  "Food & Drink Shop",
  "Juice Bar",
  "Pakistani Restaurant",
  "Hyderabadi Restaurant",
  "Sandwich Place",
  "Market",
  "Trail",
  "Event Space",
  "Lake",
  "Cosmetics Shop",
  "Multiplex",
  "Golf Course",
  "Food Truck",
  "Cafeteria",
  "ATM",
  "Roof Deck",
  "Food Court",
  "Bus Station",
  "Bus Line",
  "Hospital",
  "Bus Stop",
  "Farmers Market",
  "History Museum",
  "Sports Bar",
  "Supermarket",
  "Pool",
  "Performing Arts Venue",
  "Neighborhood",
  "Salad Place",
  "Indian Chinese Restaurant",
  "Hookah Bar",
  "Bengali Restaurant",
  "Boarding House",
  "Jewelry Store",
  "Convenience Store",
  "Metro Station",
  "Beer Garden",
  "Bowling Alley",
  "Gas Station",
  "Rajasthani Restaurant",
  "Beer Bar",
  "Train Station",
  "Playground",
  "Liquor Store",
  "Gym Pool",
  "Lighthouse",
  "Platform",
  "Boxing Gym",
  "Dance Studio",
  "General Entertainment",
  "Flea Market",
  "Historic Site",
  "Big Box Store",
  "Parsi Restaurant",
  "Bistro",
  "Science Museum",
  "Field",
  "Art Museum",
  "Monument / Landmark",
  "Wine Shop",
  "Badminton Court",
  "Planetarium",
  "Pool Hall",
  "Punjabi Restaurant",
  "Caribbean Restaurant",
  "Turkish Restaurant",
  "Financial or Legal Service",
  "Men's Store",
  "Recreation Center",
  "Hill",
  "Chaat Place",
  "Gourmet Shop",
  "Kebab Restaurant",
  "Chettinad Restaurant",
  "North Indian Restaurant",
  "Maharashtrian Restaurant",
  "Indie Movie Theater",
  "Soccer Field",
  "Kerala Restaurant",
  "Moving Target",
  "Travel & Transport",
  "Business Service",
  "Other Great Outdoors",
  "Bike Shop",
  "Gastropub",
  "Paper / Office Supplies Store",
  "Udupi Restaurant",
  "Intersection",
  "Airport Terminal",
  "Light Rail Station",
  "Multicuisine Indian Restaurant",
  "Bridge",
  "Grocery Store",
  "Pharmacy",
  "Office",
  "Sporting Goods Shop",
  "Creperie",
  "Dim Sum Restaurant",
  "Noodle House",
  "Auto Workshop",
  "Salon / Barbershop",
  "Falafel Restaurant",
  "Food",
  "Hotel Pool",
  "Halal Restaurant",
  "Kids Store",
  "Food Service",
  "Construction & Landscaping",
  "Building",
  "Resort",
  "Garden",
  "Bank",
  "Smoke Shop",
  "Food Stand",
  "Coworking Space",
  "Basketball Court",
  "Tourist Information Center",
  "Mobile Phone Shop",
  "Yoga Studio",
  "Auto Garage",
  "Automotive Shop",
  "Shop & Service",
  "Southern / Soul Food Restaurant",
  "Health Food Store",
  "Garden Center",
  "Dumpling Restaurant",
  "Szechuan Restaurant",
  "Road",
  "Toll Booth",
  "Buffet",
  "Paintball Field",
  "Shopping Plaza",
  "Dive Bar",
  "Racecourse",
  "Indian Sweet Shop",
  "Airport",
  "Castle",
  "Comfort Food Restaurant",
  "Tibetan Restaurant",
  "Scenic Lookout",
  "Farm",
  "Dry Cleaner",
]